- name: Get Docker Apt-Key
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add  docker repository
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu "{{ ansible_distribution_release }}" stable'
    state: present
    filename: docker

- name: Installing docker pkgs
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  apt:
    autoremove: true
    pkg: "{{ docker_pkgs }}"