- name: Installing Jenkins pkgs
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  apt:
    force: yes
    autoremove: yes
    pkg: "{{ jenkins_pkgs }}"

- name: Get jenkins admin Password
  command: "cat  /var/lib/jenkins/secrets/initialAdminPassword"
  register:  out

- name: Set Password Variable
  set_fact:
    jenkins_password: "{{ out.stdout }}"

- name: debug
  debug:
    msg: "password: {{jenkins_password}}"