---
# tasks file for part24-jenkins-jcasc
- include_tasks: dns-update.yml
  tags: dns
- import_tasks: update.yml
  tags: update
- import_tasks: add-repository.yml
  tags: add-repo
- import_tasks: install-docker.yml
  tags: docker
- import_tasks: install-jenkins.yml
  tags: jenkins
- import_tasks: install-plugins.yml
  tags: jenkins-plugin
- import_tasks: jenkins-jcasc.yml
  tags: jcasc
