---
# handlers file for part24-jenkins-jcasc
- name: reload jenkins systemd
  systemd:
    name: jenkins
    daemon_reload: true
    
- name: restart jenkins
  service:
    name: jenkins
    state: restarted
    enabled: true