- name: Create json of minio IPs
  vars:
    ip_list: ""
  set_fact:
        ip_list: |
          '{%- for host in groups['all'] -%}{"ip":"{{hostvars[host]['ansible_host']}}"}{%- if not loop.last -%},{%- endif -%}{%- endfor -%}'
  run_once: true
  tags: 
    - dns

- name: Update DNS record of minio address
  script:
    cmd: "files/update-dns.sh -a \"{{(lookup('env','ARVANDNSAPIKEY'))}}\" -d \"{{minio_fqdn}}\" -i {{ip_list}}"
  delegate_to: localhost
  run_once: true
  tags: 
    - dns