- name: Create minio group
  group:
    name: "{{ minio_group }}"
    system: true
    state: present

- name: Create minio user
  user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    system: true
    create_home: false
    shell: "/usr/sbin/nologin"
- name: stop minio
  service:
    name: minio
    state: stopped
  ignore_errors: true

- name: remove minio storage minio path
  file:
    path: "{{ item.mount_point }}/minio"
    state: absent
  with_items: "{{ minio_drive }}"

- name: Create minio storage minio path
  file:
    path: "{{ item.mount_point }}/minio"
    state: directory
    recurse: true
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0755
  with_items: "{{ minio_drive }}"

- name: Get minio binary file
  get_url:
   #url: "{{ _minio_download_url }}"
   url: http://78.157.56.121/minio
   dest: "{{ minio_bin_path }}"
   owner: "root"
   group: "root"
   timeout: 60
   mode: 0755

# - name: Minio offline release
#   copy:
#     src: /download/minio
#     dst: "{{ minio_bin_path }}/minio"
#     owner: "root"
#     group: "root"
#     mode: 0755