- name: Create minio group
  group:
    name: "{{ minio_group }}"
    state: present

- name: Create minio user
  user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    system: "yes"
    shell: "/usr/sbin/nologin"

- name: Create minio storage minio path
  file:
    path: "{{ minio_storage_path }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0755


- name: Get minio binary file
  get_url:
   #url: "{{ _minio_download_url }}"
   url: http://78.157.56.121/minio
   dest: "{{ minio_bin_path }}"
   owner: "root"
   group: "root"
   timeout: 60
   mode: 0755

# - name: Minio offline release
#   copy:
#     src: /download/minio
#     dst: "{{ minio_bin_path }}/minio"
#     owner: "root"
#     group: "root"
#     mode: 0755