---
# handlers file for setup-minio
- name: reload minio systemd
  systemd:
    name: minio
    daemon_reload: true
    
- name: restart minio
  service:
    name: minio
    state: restarted
    enabled: true

